name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install numpy first
        pip install numpy==1.23.5
        # Install other core dependencies
        pip install flask==2.0.1 Werkzeug==2.0.1
        # Install ML dependencies
        pip install scikit-learn==1.0.2 pandas==1.3.0 joblib==1.3.2
        # Install test dependencies
        pip install pytest==7.4.3 pytest-cov==4.1.0 flake8==6.1.0
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -c "import sys; print(f'Python version: {sys.version}')"
        python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"
        python -c "import sklearn; print(f'Scikit-learn version: {sklearn.__version__}')"
        pytest -v --cov=./ --cov-report=xml
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false